name: BuilDa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.2
  - more-itertools=10.6.0
  - pip=25.0.1 
  - pip:
      - json-five==1.1.2
      - fmpy==0.3.22
      - matplotlib==3.10.1 
      - numpy==2.2.4
      - pandas==2.2.3
      - plotly==6.0.0
      - regex==2024.11.6
      - scipy==1.15.2 
